spring:
  main:
    allow-circular-references: true
  datasource:
      url: jdbc:mariadb://localhost:3306/oauthlogin
      username: root
      password: 4316
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 30990090247-5n0u80ccosfeeie1msb4ovg7klpfhem2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            clientId: KqxeOZGiteDGNsYKDqMC
            clientSecret: qmMGp0m9Em
            scope:
              - name
              - email
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.